import { getDb } from "../api/queries/connection";
import { categories, subcategories, products, websiteSettings } from "@db/schema";

async function seed() {
  const db = getDb();
  console.log("Seeding database...");

  // ==================== CATEGORIES ====================
  console.log("Inserting categories...");
  const cats = [
    { slug: "engine-parts", name: "Engine Parts", description: "Oil filters, air filters, spark plugs, timing belts, radiators and all engine components", image: "/images/categories/engine-parts.jpg", sortOrder: 1 },
    { slug: "brake-system", name: "Brake System", description: "Brake pads, brake discs, brake calipers, brake shoes and ABS sensors", image: "/images/categories/brake-system.jpg", sortOrder: 2 },
    { slug: "suspension-parts", name: "Suspension Parts", description: "Shock absorbers, control arms, ball joints, tie rod ends and coil springs", image: "/images/categories/suspension-parts.jpg", sortOrder: 3 },
    { slug: "electrical-parts", name: "Electrical Parts", description: "Batteries, alternators, starters, sensors, fuses, relays and ignition coils", image: "/images/categories/electrical-parts.jpg", sortOrder: 4 },
    { slug: "lights", name: "Lights", description: "Headlights, tail lights, fog lights, indicator lights and LED bulbs", image: "/images/categories/lights.jpg", sortOrder: 5 },
    { slug: "body-parts", name: "Body Parts", description: "Bumpers, fenders, bonnet, doors, side mirrors and grills", image: "/images/categories/body-parts.jpg", sortOrder: 6 },
    { slug: "oils-fluids", name: "Oils & Fluids", description: "Engine oil, gear oil, brake fluid, coolant and transmission oil", image: "/images/categories/oils-fluids.jpg", sortOrder: 7 },
    { slug: "accessories", name: "Accessories", description: "Floor mats, seat covers, wipers, car covers and mobile holders", image: "/images/categories/accessories.jpg", sortOrder: 8 },
  ];
  
  for (const cat of cats) {
    await db.insert(categories).values(cat).onDuplicateKeyUpdate({
      set: cat,
    });
  }

  // Get category IDs
  const dbCats = await db.select().from(categories);
  const catMap: Record<string, number> = {};
  for (const c of dbCats) {
    catMap[c.slug] = c.id;
  }

  // ==================== SUBCATEGORIES ====================
  console.log("Inserting subcategories...");
  const subs = [
    // Engine Parts
    { categoryId: catMap["engine-parts"], slug: "oil-filters", name: "Oil Filters", sortOrder: 1 },
    { categoryId: catMap["engine-parts"], slug: "air-filters", name: "Air Filters", sortOrder: 2 },
    { categoryId: catMap["engine-parts"], slug: "fuel-filters", name: "Fuel Filters", sortOrder: 3 },
    { categoryId: catMap["engine-parts"], slug: "spark-plugs", name: "Spark Plugs", sortOrder: 4 },
    { categoryId: catMap["engine-parts"], slug: "timing-belts", name: "Timing Belts", sortOrder: 5 },
    { categoryId: catMap["engine-parts"], slug: "engine-mounts", name: "Engine Mounts", sortOrder: 6 },
    { categoryId: catMap["engine-parts"], slug: "radiators", name: "Radiators", sortOrder: 7 },
    { categoryId: catMap["engine-parts"], slug: "water-pumps", name: "Water Pumps", sortOrder: 8 },
    // Brake System
    { categoryId: catMap["brake-system"], slug: "brake-pads", name: "Brake Pads", sortOrder: 1 },
    { categoryId: catMap["brake-system"], slug: "brake-shoes", name: "Brake Shoes", sortOrder: 2 },
    { categoryId: catMap["brake-system"], slug: "brake-discs", name: "Brake Discs", sortOrder: 3 },
    { categoryId: catMap["brake-system"], slug: "brake-calipers", name: "Brake Calipers", sortOrder: 4 },
    { categoryId: catMap["brake-system"], slug: "brake-oil", name: "Brake Oil", sortOrder: 5 },
    { categoryId: catMap["brake-system"], slug: "abs-sensors", name: "ABS Sensors", sortOrder: 6 },
    // Suspension Parts
    { categoryId: catMap["suspension-parts"], slug: "shock-absorbers", name: "Shock Absorbers", sortOrder: 1 },
    { categoryId: catMap["suspension-parts"], slug: "control-arms", name: "Control Arms", sortOrder: 2 },
    { categoryId: catMap["suspension-parts"], slug: "ball-joints", name: "Ball Joints", sortOrder: 3 },
    { categoryId: catMap["suspension-parts"], slug: "tie-rod-ends", name: "Tie Rod Ends", sortOrder: 4 },
    { categoryId: catMap["suspension-parts"], slug: "bushings", name: "Bushings", sortOrder: 5 },
    { categoryId: catMap["suspension-parts"], slug: "springs", name: "Springs", sortOrder: 6 },
    // Electrical Parts
    { categoryId: catMap["electrical-parts"], slug: "batteries", name: "Batteries", sortOrder: 1 },
    { categoryId: catMap["electrical-parts"], slug: "alternators", name: "Alternators", sortOrder: 2 },
    { categoryId: catMap["electrical-parts"], slug: "starters", name: "Starters", sortOrder: 3 },
    { categoryId: catMap["electrical-parts"], slug: "sensors", name: "Sensors", sortOrder: 4 },
    { categoryId: catMap["electrical-parts"], slug: "fuses", name: "Fuses", sortOrder: 5 },
    { categoryId: catMap["electrical-parts"], slug: "ignition-coils", name: "Ignition Coils", sortOrder: 6 },
    // Lights
    { categoryId: catMap["lights"], slug: "headlights", name: "Headlights", sortOrder: 1 },
    { categoryId: catMap["lights"], slug: "tail-lights", name: "Tail Lights", sortOrder: 2 },
    { categoryId: catMap["lights"], slug: "fog-lights", name: "Fog Lights", sortOrder: 3 },
    { categoryId: catMap["lights"], slug: "indicator-lights", name: "Indicator Lights", sortOrder: 4 },
    { categoryId: catMap["lights"], slug: "led-bulbs", name: "LED Bulbs", sortOrder: 5 },
    // Body Parts
    { categoryId: catMap["body-parts"], slug: "bumpers", name: "Bumpers", sortOrder: 1 },
    { categoryId: catMap["body-parts"], slug: "fenders", name: "Fenders", sortOrder: 2 },
    { categoryId: catMap["body-parts"], slug: "bonnet", name: "Bonnet", sortOrder: 3 },
    { categoryId: catMap["body-parts"], slug: "doors", name: "Doors", sortOrder: 4 },
    { categoryId: catMap["body-parts"], slug: "side-mirrors", name: "Side Mirrors", sortOrder: 5 },
    { categoryId: catMap["body-parts"], slug: "grills", name: "Grills", sortOrder: 6 },
    // Oils & Fluids
    { categoryId: catMap["oils-fluids"], slug: "engine-oil", name: "Engine Oil", sortOrder: 1 },
    { categoryId: catMap["oils-fluids"], slug: "gear-oil", name: "Gear Oil", sortOrder: 2 },
    { categoryId: catMap["oils-fluids"], slug: "brake-fluid", name: "Brake Fluid", sortOrder: 3 },
    { categoryId: catMap["oils-fluids"], slug: "coolant", name: "Coolant", sortOrder: 4 },
    { categoryId: catMap["oils-fluids"], slug: "transmission-oil", name: "Transmission Oil", sortOrder: 5 },
    // Accessories
    { categoryId: catMap["accessories"], slug: "floor-mats", name: "Floor Mats", sortOrder: 1 },
    { categoryId: catMap["accessories"], slug: "seat-covers", name: "Seat Covers", sortOrder: 2 },
    { categoryId: catMap["accessories"], slug: "wipers", name: "Wipers", sortOrder: 3 },
    { categoryId: catMap["accessories"], slug: "car-covers", name: "Car Covers", sortOrder: 4 },
    { categoryId: catMap["accessories"], slug: "mobile-holders", name: "Mobile Holders", sortOrder: 5 },
  ];

  for (const sub of subs) {
    await db.insert(subcategories).values(sub).onDuplicateKeyUpdate({
      set: sub,
    });
  }

  // Get subcategory IDs
  const dbSubs = await db.select().from(subcategories);
  const subMap: Record<string, number> = {};
  for (const s of dbSubs) {
    subMap[s.slug] = s.id;
  }

  // ==================== PRODUCTS ====================
  console.log("Inserting products...");
  const productData = [
    // ===== OIL FILTERS =====
    { sku: "OF-ALT-001", name: "Suzuki Alto Oil Filter", slug: "suzuki-alto-oil-filter", description: "Genuine quality oil filter for Suzuki Alto. Keeps your engine clean and running smoothly.", specifications: "Thread: M20x1.5\nHeight: 65mm\nOuter Diameter: 68mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Suzuki", carModel: "Alto", yearFrom: 2000, yearTo: 2024, engineVariant: "660cc / 800cc", condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "450.00", sellingPrice: "850.00", marketPriceMin: "800.00", marketPriceMax: "1800.00", stockQuantity: 45, minStockAlert: 10, warranty: "1 Month", returnPolicy: "7 days replacement" },
    { sku: "OF-ALT-002", name: "Suzuki Alto Oil Filter (OEM)", slug: "suzuki-alto-oil-filter-oem", description: "OEM quality oil filter for Suzuki Alto. Best value for money.", specifications: "Thread: M20x1.5\nHeight: 65mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Suzuki", carModel: "Alto", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "350.00", sellingPrice: "650.00", marketPriceMin: "600.00", marketPriceMax: "1200.00", stockQuantity: 60, warranty: "1 Month", returnPolicy: "7 days replacement" },
    { sku: "OF-CUL-001", name: "Suzuki Cultus Oil Filter", slug: "suzuki-cultus-oil-filter", description: "Genuine oil filter for Suzuki Cultus. Perfect fit and filtration.", specifications: "Thread: M20x1.5\nHeight: 75mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Suzuki", carModel: "Cultus", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "500.00", sellingPrice: "950.00", marketPriceMin: "900.00", marketPriceMax: "1800.00", stockQuantity: 38, warranty: "1 Month" },
    { sku: "OF-SWI-001", name: "Suzuki Swift Oil Filter", slug: "suzuki-swift-oil-filter", description: "Premium oil filter for Suzuki Swift. High flow rate design.", specifications: "Thread: M20x1.5\nHeight: 80mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Suzuki", carModel: "Swift", yearFrom: 2010, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "600.00", sellingPrice: "1100.00", marketPriceMin: "1000.00", marketPriceMax: "2000.00", stockQuantity: 32, warranty: "1 Month" },
    { sku: "OF-COR-001", name: "Toyota Corolla Oil Filter", slug: "toyota-corolla-oil-filter", description: "Genuine Toyota Corolla oil filter. Superior filtration technology.", specifications: "Thread: M20x1.5\nHeight: 85mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "700.00", sellingPrice: "1350.00", marketPriceMin: "1200.00", marketPriceMax: "2500.00", stockQuantity: 50, warranty: "1 Month" },
    { sku: "OF-COR-002", name: "Toyota Corolla Oil Filter (OEM)", slug: "toyota-corolla-oil-filter-oem", description: "OEM quality oil filter for Toyota Corolla. Reliable and affordable.", specifications: "Thread: M20x1.5\nHeight: 85mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "500.00", sellingPrice: "950.00", marketPriceMin: "800.00", marketPriceMax: "1800.00", stockQuantity: 55, warranty: "1 Month" },
    { sku: "OF-YAR-001", name: "Toyota Yaris Oil Filter", slug: "toyota-yaris-oil-filter", description: "Genuine oil filter for Toyota Yaris. Precision engineered.", specifications: "Thread: M20x1.5\nHeight: 75mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Toyota", carModel: "Yaris", yearFrom: 2016, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "650.00", sellingPrice: "1200.00", marketPriceMin: "1100.00", marketPriceMax: "2200.00", stockQuantity: 28, warranty: "1 Month" },
    { sku: "OF-CIV-001", name: "Honda Civic Oil Filter", slug: "honda-civic-oil-filter", description: "Genuine Honda Civic oil filter. High efficiency media.", specifications: "Thread: M20x1.5\nHeight: 80mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "750.00", sellingPrice: "1400.00", marketPriceMin: "1300.00", marketPriceMax: "2600.00", stockQuantity: 42, warranty: "1 Month" },
    { sku: "OF-CIV-002", name: "Honda Civic Oil Filter (OEM)", slug: "honda-civic-oil-filter-oem", description: "OEM quality oil filter for Honda Civic.", specifications: "Thread: M20x1.5\nHeight: 80mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "550.00", sellingPrice: "1050.00", marketPriceMin: "950.00", marketPriceMax: "1800.00", stockQuantity: 48, warranty: "1 Month" },
    { sku: "OF-CIT-001", name: "Honda City Oil Filter", slug: "honda-city-oil-filter", description: "Genuine oil filter for Honda City.", specifications: "Thread: M20x1.5\nHeight: 75mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Honda", carModel: "City", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "650.00", sellingPrice: "1200.00", marketPriceMin: "1100.00", marketPriceMax: "2200.00", stockQuantity: 35, warranty: "1 Month" },
    { sku: "OF-SPO-001", name: "Kia Sportage Oil Filter", slug: "kia-sportage-oil-filter", description: "Genuine oil filter for Kia Sportage.", specifications: "Thread: M20x1.5\nHeight: 90mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Kia", carModel: "Sportage", yearFrom: 2018, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "900.00", sellingPrice: "1700.00", marketPriceMin: "1500.00", marketPriceMax: "3000.00", stockQuantity: 20, warranty: "1 Month" },
    { sku: "OF-ELA-001", name: "Hyundai Elantra Oil Filter", slug: "hyundai-elantra-oil-filter", description: "Genuine oil filter for Hyundai Elantra.", specifications: "Thread: M20x1.5\nHeight: 85mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Hyundai", carModel: "Elantra", yearFrom: 2010, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "800.00", sellingPrice: "1500.00", marketPriceMin: "1300.00", marketPriceMax: "2800.00", stockQuantity: 22, warranty: "1 Month" },
    { sku: "OF-DAY-001", name: "Nissan Dayz Oil Filter", slug: "nissan-dayz-oil-filter", description: "Genuine oil filter for Nissan Dayz.", specifications: "Thread: M20x1.5\nHeight: 65mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Nissan", carModel: "Dayz", yearFrom: 2013, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "550.00", sellingPrice: "1050.00", marketPriceMin: "950.00", marketPriceMax: "1800.00", stockQuantity: 15, warranty: "1 Month" },
    { sku: "OF-BMW-001", name: "BMW 3 Series Oil Filter", slug: "bmw-3-series-oil-filter", description: "Genuine BMW 3 Series oil filter.", specifications: "Thread: M22x1.5\nHeight: 95mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "BMW", carModel: "3 Series", yearFrom: 2005, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "1800.00", sellingPrice: "3500.00", marketPriceMin: "3200.00", marketPriceMax: "6500.00", stockQuantity: 12, warranty: "1 Month" },
    { sku: "OF-MER-001", name: "Mercedes C-Class Oil Filter", slug: "mercedes-c-class-oil-filter", description: "Genuine Mercedes C-Class oil filter.", specifications: "Thread: M22x1.5\nHeight: 100mm", image: "/images/products/engine/oil-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["oil-filters"], carBrand: "Mercedes", carModel: "C-Class", yearFrom: 2007, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "2000.00", sellingPrice: "3800.00", marketPriceMin: "3500.00", marketPriceMax: "7000.00", stockQuantity: 10, warranty: "1 Month" },

    // ===== AIR FILTERS =====
    { sku: "AF-COR-001", name: "Toyota Corolla Air Filter", slug: "toyota-corolla-air-filter", description: "Genuine Toyota Corolla air filter. Optimal airflow and filtration.", specifications: "Dimensions: 220x180x45mm\nType: Panel Filter", image: "/images/products/engine/air-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["air-filters"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "600.00", sellingPrice: "1200.00", marketPriceMin: "1000.00", marketPriceMax: "2200.00", stockQuantity: 40, warranty: "1 Month" },
    { sku: "AF-CIV-001", name: "Honda Civic Air Filter", slug: "honda-civic-air-filter", description: "Genuine Honda Civic air filter. High dust holding capacity.", specifications: "Dimensions: 230x170x50mm\nType: Panel Filter", image: "/images/products/engine/air-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["air-filters"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "700.00", sellingPrice: "1400.00", marketPriceMin: "1200.00", marketPriceMax: "2500.00", stockQuantity: 35, warranty: "1 Month" },
    { sku: "AF-CIV-002", name: "Honda Civic Air Filter (OEM)", slug: "honda-civic-air-filter-oem", description: "OEM quality air filter for Honda Civic.", specifications: "Dimensions: 230x170x50mm", image: "/images/products/engine/air-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["air-filters"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "450.00", sellingPrice: "900.00", marketPriceMin: "800.00", marketPriceMax: "1600.00", stockQuantity: 50, warranty: "1 Month" },
    { sku: "AF-CIT-001", name: "Honda City Air Filter", slug: "honda-city-air-filter", description: "Genuine air filter for Honda City.", specifications: "Dimensions: 210x160x45mm", image: "/images/products/engine/air-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["air-filters"], carBrand: "Honda", carModel: "City", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "550.00", sellingPrice: "1100.00", marketPriceMin: "950.00", marketPriceMax: "1900.00", stockQuantity: 38, warranty: "1 Month" },
    { sku: "AF-ALT-001", name: "Suzuki Alto Air Filter", slug: "suzuki-alto-air-filter", description: "Genuine air filter for Suzuki Alto.", specifications: "Dimensions: 180x140x40mm", image: "/images/products/engine/air-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["air-filters"], carBrand: "Suzuki", carModel: "Alto", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "400.00", sellingPrice: "800.00", marketPriceMin: "700.00", marketPriceMax: "1400.00", stockQuantity: 55, warranty: "1 Month" },
    { sku: "AF-CUL-001", name: "Suzuki Cultus Air Filter", slug: "suzuki-cultus-air-filter", description: "Genuine air filter for Suzuki Cultus.", specifications: "Dimensions: 190x150x42mm", image: "/images/products/engine/air-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["air-filters"], carBrand: "Suzuki", carModel: "Cultus", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "450.00", sellingPrice: "900.00", marketPriceMin: "800.00", marketPriceMax: "1600.00", stockQuantity: 42, warranty: "1 Month" },
    { sku: "AF-SPO-001", name: "Kia Sportage Air Filter", slug: "kia-sportage-air-filter", description: "Genuine air filter for Kia Sportage.", specifications: "Dimensions: 250x190x55mm", image: "/images/products/engine/air-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["air-filters"], carBrand: "Kia", carModel: "Sportage", yearFrom: 2018, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "800.00", sellingPrice: "1600.00", marketPriceMin: "1400.00", marketPriceMax: "2800.00", stockQuantity: 18, warranty: "1 Month" },
    { sku: "AF-SWI-001", name: "Suzuki Swift Air Filter", slug: "suzuki-swift-air-filter", description: "Genuine air filter for Suzuki Swift.", specifications: "Dimensions: 200x160x45mm", image: "/images/products/engine/air-filter-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["air-filters"], carBrand: "Suzuki", carModel: "Swift", yearFrom: 2010, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "500.00", sellingPrice: "1000.00", marketPriceMin: "900.00", marketPriceMax: "1800.00", stockQuantity: 30, warranty: "1 Month" },

    // ===== SPARK PLUGS =====
    { sku: "SP-COR-001", name: "Toyota Corolla Spark Plug (Set of 4)", slug: "toyota-corolla-spark-plug", description: "Genuine iridium spark plugs for Toyota Corolla. Long lasting performance.", specifications: "Thread: M14x1.25\nHex: 16mm\nGap: 1.1mm", image: "/images/products/engine/spark-plug-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["spark-plugs"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "1200.00", sellingPrice: "2400.00", marketPriceMin: "2000.00", marketPriceMax: "4000.00", stockQuantity: 25, warranty: "3 Months" },
    { sku: "SP-CIV-001", name: "Honda Civic Spark Plug (Set of 4)", slug: "honda-civic-spark-plug", description: "Genuine iridium spark plugs for Honda Civic.", specifications: "Thread: M14x1.25\nGap: 1.1mm", image: "/images/products/engine/spark-plug-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["spark-plugs"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "1400.00", sellingPrice: "2800.00", marketPriceMin: "2400.00", marketPriceMax: "4800.00", stockQuantity: 22, warranty: "3 Months" },
    { sku: "SP-ALT-001", name: "Suzuki Alto Spark Plug (Set of 3)", slug: "suzuki-alto-spark-plug", description: "Genuine spark plugs for Suzuki Alto.", specifications: "Thread: M14x1.25\nGap: 0.8mm", image: "/images/products/engine/spark-plug-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["spark-plugs"], carBrand: "Suzuki", carModel: "Alto", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "600.00", sellingPrice: "1200.00", marketPriceMin: "1000.00", marketPriceMax: "2000.00", stockQuantity: 40, warranty: "3 Months" },
    { sku: "SP-CUL-001", name: "Suzuki Cultus Spark Plug (Set of 4)", slug: "suzuki-cultus-spark-plug", description: "Genuine spark plugs for Suzuki Cultus.", specifications: "Thread: M14x1.25\nGap: 1.0mm", image: "/images/products/engine/spark-plug-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["spark-plugs"], carBrand: "Suzuki", carModel: "Cultus", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "700.00", sellingPrice: "1400.00", marketPriceMin: "1200.00", marketPriceMax: "2400.00", stockQuantity: 35, warranty: "3 Months" },

    // ===== RADIATORS =====
    { sku: "RD-COR-001", name: "Toyota Corolla Radiator", slug: "toyota-corolla-radiator", description: "Aluminum radiator for Toyota Corolla. Efficient cooling performance.", specifications: "Core Size: 400x600x26mm\nInlet/Outlet: 32mm", image: "/images/products/engine/radiator-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["radiators"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "4500.00", sellingPrice: "8500.00", marketPriceMin: "8000.00", marketPriceMax: "15000.00", stockQuantity: 12, warranty: "6 Months" },
    { sku: "RD-CIV-001", name: "Honda Civic Radiator", slug: "honda-civic-radiator", description: "Aluminum radiator for Honda Civic.", specifications: "Core Size: 380x580x26mm", image: "/images/products/engine/radiator-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["radiators"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "5000.00", sellingPrice: "9500.00", marketPriceMin: "8500.00", marketPriceMax: "16000.00", stockQuantity: 10, warranty: "6 Months" },
    { sku: "RD-ALT-001", name: "Suzuki Alto Radiator", slug: "suzuki-alto-radiator", description: "Aluminum radiator for Suzuki Alto.", specifications: "Core Size: 300x450x22mm", image: "/images/products/engine/radiator-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["radiators"], carBrand: "Suzuki", carModel: "Alto", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "3500.00", sellingPrice: "6500.00", marketPriceMin: "6000.00", marketPriceMax: "11000.00", stockQuantity: 15, warranty: "6 Months" },
    { sku: "RD-CUL-001", name: "Suzuki Cultus Radiator", slug: "suzuki-cultus-radiator", description: "Aluminum radiator for Suzuki Cultus.", specifications: "Core Size: 320x480x24mm", image: "/images/products/engine/radiator-generic.jpg", categoryId: catMap["engine-parts"], subcategoryId: subMap["radiators"], carBrand: "Suzuki", carModel: "Cultus", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "3800.00", sellingPrice: "7200.00", marketPriceMin: "6500.00", marketPriceMax: "12000.00", stockQuantity: 12, warranty: "6 Months" },

    // ===== BRAKE PADS =====
    { sku: "BP-COR-001", name: "Toyota Corolla Front Brake Pads", slug: "toyota-corolla-brake-pads", description: "Genuine front brake pads for Toyota Corolla. Superior stopping power.", specifications: "Position: Front\nMaterial: Ceramic\nAxle Set: 4 pads", image: "/images/products/brake/brake-pads-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-pads"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "2500.00", sellingPrice: "4800.00", marketPriceMin: "4500.00", marketPriceMax: "9500.00", stockQuantity: 30, warranty: "3 Months" },
    { sku: "BP-COR-002", name: "Toyota Corolla Front Brake Pads (OEM)", slug: "toyota-corolla-brake-pads-oem", description: "OEM front brake pads for Toyota Corolla.", specifications: "Position: Front\nAxle Set: 4 pads", image: "/images/products/brake/brake-pads-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-pads"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "1800.00", sellingPrice: "3500.00", marketPriceMin: "3000.00", marketPriceMax: "6000.00", stockQuantity: 45, warranty: "3 Months" },
    { sku: "BP-CIV-001", name: "Honda Civic Front Brake Pads", slug: "honda-civic-brake-pads", description: "Genuine front brake pads for Honda Civic.", specifications: "Position: Front\nMaterial: Ceramic\nAxle Set: 4 pads", image: "/images/products/brake/brake-pads-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-pads"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "3000.00", sellingPrice: "5800.00", marketPriceMin: "5500.00", marketPriceMax: "12000.00", stockQuantity: 25, warranty: "3 Months" },
    { sku: "BP-CIV-002", name: "Honda Civic Front Brake Pads (OEM)", slug: "honda-civic-brake-pads-oem", description: "OEM front brake pads for Honda Civic.", specifications: "Position: Front\nAxle Set: 4 pads", image: "/images/products/brake/brake-pads-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-pads"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "2200.00", sellingPrice: "4200.00", marketPriceMin: "3800.00", marketPriceMax: "7500.00", stockQuantity: 38, warranty: "3 Months" },
    { sku: "BP-CIT-001", name: "Honda City Front Brake Pads", slug: "honda-city-brake-pads", description: "Genuine front brake pads for Honda City.", specifications: "Position: Front\nAxle Set: 4 pads", image: "/images/products/brake/brake-pads-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-pads"], carBrand: "Honda", carModel: "City", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "2200.00", sellingPrice: "4200.00", marketPriceMin: "3800.00", marketPriceMax: "8000.00", stockQuantity: 30, warranty: "3 Months" },
    { sku: "BP-ALT-001", name: "Suzuki Alto Front Brake Pads", slug: "suzuki-alto-brake-pads", description: "Genuine front brake pads for Suzuki Alto.", specifications: "Position: Front\nAxle Set: 4 pads", image: "/images/products/brake/brake-pads-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-pads"], carBrand: "Suzuki", carModel: "Alto", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "900.00", sellingPrice: "1800.00", marketPriceMin: "1600.00", marketPriceMax: "3200.00", stockQuantity: 55, warranty: "3 Months" },
    { sku: "BP-CUL-001", name: "Suzuki Cultus Front Brake Pads", slug: "suzuki-cultus-brake-pads", description: "Genuine front brake pads for Suzuki Cultus.", specifications: "Position: Front\nAxle Set: 4 pads", image: "/images/products/brake/brake-pads-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-pads"], carBrand: "Suzuki", carModel: "Cultus", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "1200.00", sellingPrice: "2400.00", marketPriceMin: "2000.00", marketPriceMax: "4000.00", stockQuantity: 40, warranty: "3 Months" },
    { sku: "BP-SWI-001", name: "Suzuki Swift Front Brake Pads", slug: "suzuki-swift-brake-pads", description: "Genuine front brake pads for Suzuki Swift.", specifications: "Position: Front\nAxle Set: 4 pads", image: "/images/products/brake/brake-pads-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-pads"], carBrand: "Suzuki", carModel: "Swift", yearFrom: 2010, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "1500.00", sellingPrice: "3000.00", marketPriceMin: "2600.00", marketPriceMax: "5200.00", stockQuantity: 28, warranty: "3 Months" },
    { sku: "BP-SPO-001", name: "Kia Sportage Front Brake Pads", slug: "kia-sportage-brake-pads", description: "Genuine front brake pads for Kia Sportage.", specifications: "Position: Front\nAxle Set: 4 pads", image: "/images/products/brake/brake-pads-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-pads"], carBrand: "Kia", carModel: "Sportage", yearFrom: 2018, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "3500.00", sellingPrice: "6800.00", marketPriceMin: "6000.00", marketPriceMax: "12000.00", stockQuantity: 15, warranty: "3 Months" },
    { sku: "BP-ELA-001", name: "Hyundai Elantra Front Brake Pads", slug: "hyundai-elantra-brake-pads", description: "Genuine front brake pads for Hyundai Elantra.", specifications: "Position: Front\nAxle Set: 4 pads", image: "/images/products/brake/brake-pads-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-pads"], carBrand: "Hyundai", carModel: "Elantra", yearFrom: 2010, yearTo: 2024, condition: "new" as const, qualityType: "genuine" as const, purchasePrice: "2800.00", sellingPrice: "5500.00", marketPriceMin: "4800.00", marketPriceMax: "9500.00", stockQuantity: 18, warranty: "3 Months" },

    // ===== BRAKE DISCS =====
    { sku: "BD-COR-001", name: "Toyota Corolla Front Brake Disc (Pair)", slug: "toyota-corolla-brake-disc", description: "Front brake disc pair for Toyota Corolla. Vented design.", specifications: "Position: Front\nDiameter: 275mm\nVented: Yes", image: "/images/products/brake/brake-disc-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-discs"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "3500.00", sellingPrice: "6800.00", marketPriceMin: "6000.00", marketPriceMax: "12000.00", stockQuantity: 15, warranty: "6 Months" },
    { sku: "BD-CIV-001", name: "Honda Civic Front Brake Disc (Pair)", slug: "honda-civic-brake-disc", description: "Front brake disc pair for Honda Civic.", specifications: "Position: Front\nDiameter: 262mm", image: "/images/products/brake/brake-disc-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-discs"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "4000.00", sellingPrice: "7800.00", marketPriceMin: "7000.00", marketPriceMax: "14000.00", stockQuantity: 12, warranty: "6 Months" },
    { sku: "BD-SPO-001", name: "Kia Sportage Front Brake Disc (Pair)", slug: "kia-sportage-brake-disc", description: "Front brake disc pair for Kia Sportage.", specifications: "Position: Front\nDiameter: 300mm", image: "/images/products/brake/brake-disc-generic.jpg", categoryId: catMap["brake-system"], subcategoryId: subMap["brake-discs"], carBrand: "Kia", carModel: "Sportage", yearFrom: 2018, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "5500.00", sellingPrice: "10500.00", marketPriceMin: "9500.00", marketPriceMax: "18000.00", stockQuantity: 8, warranty: "6 Months" },

    // ===== SHOCK ABSORBERS =====
    { sku: "SA-COR-001", name: "Toyota Corolla Front Shock Absorber (Pair)", slug: "toyota-corolla-shock-absorber", description: "Front shock absorber pair for Toyota Corolla. Gas filled.", specifications: "Position: Front\nType: Gas Filled\nPair: Yes", image: "/images/products/suspension/shock-absorber-generic.jpg", categoryId: catMap["suspension-parts"], subcategoryId: subMap["shock-absorbers"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "4000.00", sellingPrice: "7800.00", marketPriceMin: "7000.00", marketPriceMax: "14000.00", stockQuantity: 14, warranty: "6 Months" },
    { sku: "SA-CIV-001", name: "Honda Civic Front Shock Absorber (Pair)", slug: "honda-civic-shock-absorber", description: "Front shock absorber pair for Honda Civic.", specifications: "Position: Front\nType: Gas Filled", image: "/images/products/suspension/shock-absorber-generic.jpg", categoryId: catMap["suspension-parts"], subcategoryId: subMap["shock-absorbers"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "4500.00", sellingPrice: "8800.00", marketPriceMin: "8000.00", marketPriceMax: "16000.00", stockQuantity: 12, warranty: "6 Months" },
    { sku: "SA-ALT-001", name: "Suzuki Alto Front Shock Absorber (Pair)", slug: "suzuki-alto-shock-absorber", description: "Front shock absorber pair for Suzuki Alto.", specifications: "Position: Front\nType: Oil Filled", image: "/images/products/suspension/shock-absorber-generic.jpg", categoryId: catMap["suspension-parts"], subcategoryId: subMap["shock-absorbers"], carBrand: "Suzuki", carModel: "Alto", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "2500.00", sellingPrice: "4800.00", marketPriceMin: "4200.00", marketPriceMax: "8500.00", stockQuantity: 20, warranty: "6 Months" },
    { sku: "SA-CUL-001", name: "Suzuki Cultus Front Shock Absorber (Pair)", slug: "suzuki-cultus-shock-absorber", description: "Front shock absorber pair for Suzuki Cultus.", specifications: "Position: Front\nType: Oil Filled", image: "/images/products/suspension/shock-absorber-generic.jpg", categoryId: catMap["suspension-parts"], subcategoryId: subMap["shock-absorbers"], carBrand: "Suzuki", carModel: "Cultus", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "3000.00", sellingPrice: "5800.00", marketPriceMin: "5000.00", marketPriceMax: "10000.00", stockQuantity: 16, warranty: "6 Months" },
    { sku: "SA-SWI-001", name: "Suzuki Swift Front Shock Absorber (Pair)", slug: "suzuki-swift-shock-absorber", description: "Front shock absorber pair for Suzuki Swift.", specifications: "Position: Front\nType: Gas Filled", image: "/images/products/suspension/shock-absorber-generic.jpg", categoryId: catMap["suspension-parts"], subcategoryId: subMap["shock-absorbers"], carBrand: "Suzuki", carModel: "Swift", yearFrom: 2010, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "3500.00", sellingPrice: "6800.00", marketPriceMin: "6000.00", marketPriceMax: "12000.00", stockQuantity: 14, warranty: "6 Months" },
    { sku: "SA-SPO-001", name: "Kia Sportage Front Shock Absorber (Pair)", slug: "kia-sportage-shock-absorber", description: "Front shock absorber pair for Kia Sportage.", specifications: "Position: Front\nType: Gas Filled", image: "/images/products/suspension/shock-absorber-generic.jpg", categoryId: catMap["suspension-parts"], subcategoryId: subMap["shock-absorbers"], carBrand: "Kia", carModel: "Sportage", yearFrom: 2018, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "7000.00", sellingPrice: "13500.00", marketPriceMin: "12000.00", marketPriceMax: "24000.00", stockQuantity: 8, warranty: "6 Months" },

    // ===== BATTERIES =====
    { sku: "BT-55D23L", name: "55D23L Car Battery ( maintenance free )", slug: "55d23l-car-battery", description: "Maintenance free battery. Suitable for most Japanese sedans.", specifications: "Capacity: 60Ah\nCCA: 480A\nVoltage: 12V", image: "/images/products/electrical/battery-generic.jpg", categoryId: catMap["electrical-parts"], subcategoryId: subMap["batteries"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "8000.00", sellingPrice: "15000.00", marketPriceMin: "14000.00", marketPriceMax: "25000.00", stockQuantity: 20, warranty: "12 Months" },
    { sku: "BT-NS40ZL", name: "NS40ZL Small Car Battery", slug: "ns40zl-car-battery", description: "Compact battery for small cars like Alto, Mehran.", specifications: "Capacity: 32Ah\nCCA: 300A\nVoltage: 12V", image: "/images/products/electrical/battery-generic.jpg", categoryId: catMap["electrical-parts"], subcategoryId: subMap["batteries"], carBrand: "Suzuki", carModel: "Alto", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "6000.00", sellingPrice: "11500.00", marketPriceMin: "10000.00", marketPriceMax: "18000.00", stockQuantity: 25, warranty: "12 Months" },
    { sku: "BT-65D31L", name: "65D31L Heavy Duty Battery", slug: "65d31l-car-battery", description: "Heavy duty battery for SUVs and larger vehicles.", specifications: "Capacity: 70Ah\nCCA: 550A\nVoltage: 12V", image: "/images/products/electrical/battery-generic.jpg", categoryId: catMap["electrical-parts"], subcategoryId: subMap["batteries"], carBrand: "Kia", carModel: "Sportage", yearFrom: 2010, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "10000.00", sellingPrice: "19000.00", marketPriceMin: "17000.00", marketPriceMax: "30000.00", stockQuantity: 15, warranty: "12 Months" },
    { sku: "BT-80D26L", name: "80D26L Premium Battery", slug: "80d26l-car-battery", description: "Premium battery for luxury sedans.", specifications: "Capacity: 68Ah\nCCA: 520A\nVoltage: 12V", image: "/images/products/electrical/battery-generic.jpg", categoryId: catMap["electrical-parts"], subcategoryId: subMap["batteries"], carBrand: "Honda", carModel: "Civic", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "9500.00", sellingPrice: "18000.00", marketPriceMin: "16000.00", marketPriceMax: "28000.00", stockQuantity: 18, warranty: "12 Months" },

    // ===== HEADLIGHTS =====
    { sku: "HL-SPO-001", name: "Kia Sportage Headlight Assembly (Left)", slug: "kia-sportage-headlight-left", description: "Left headlight assembly for Kia Sportage with projector lens.", specifications: "Position: Left\nType: Projector\nBulb: H7", image: "/images/products/lights/headlight-generic.jpg", categoryId: catMap["lights"], subcategoryId: subMap["headlights"], carBrand: "Kia", carModel: "Sportage", yearFrom: 2018, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "12000.00", sellingPrice: "23000.00", marketPriceMin: "20000.00", marketPriceMax: "45000.00", stockQuantity: 6, warranty: "3 Months" },
    { sku: "HL-SPO-002", name: "Kia Sportage Headlight Assembly (Right)", slug: "kia-sportage-headlight-right", description: "Right headlight assembly for Kia Sportage with projector lens.", specifications: "Position: Right\nType: Projector\nBulb: H7", image: "/images/products/lights/headlight-generic.jpg", categoryId: catMap["lights"], subcategoryId: subMap["headlights"], carBrand: "Kia", carModel: "Sportage", yearFrom: 2018, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "12000.00", sellingPrice: "23000.00", marketPriceMin: "20000.00", marketPriceMax: "45000.00", stockQuantity: 6, warranty: "3 Months" },
    { sku: "HL-COR-001", name: "Toyota Corolla Headlight (Left)", slug: "toyota-corolla-headlight-left", description: "Left headlight for Toyota Corolla.", specifications: "Position: Left\nType: Halogen\nBulb: H4", image: "/images/products/lights/headlight-generic.jpg", categoryId: catMap["lights"], subcategoryId: subMap["headlights"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "4500.00", sellingPrice: "8500.00", marketPriceMin: "7500.00", marketPriceMax: "15000.00", stockQuantity: 10, warranty: "3 Months" },
    { sku: "HL-COR-002", name: "Toyota Corolla Headlight (Right)", slug: "toyota-corolla-headlight-right", description: "Right headlight for Toyota Corolla.", specifications: "Position: Right\nType: Halogen\nBulb: H4", image: "/images/products/lights/headlight-generic.jpg", categoryId: catMap["lights"], subcategoryId: subMap["headlights"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "4500.00", sellingPrice: "8500.00", marketPriceMin: "7500.00", marketPriceMax: "15000.00", stockQuantity: 10, warranty: "3 Months" },
    { sku: "HL-CIV-001", name: "Honda Civic Headlight (Left)", slug: "honda-civic-headlight-left", description: "Left headlight for Honda Civic.", specifications: "Position: Left\nType: Projector", image: "/images/products/lights/headlight-generic.jpg", categoryId: catMap["lights"], subcategoryId: subMap["headlights"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "5500.00", sellingPrice: "10500.00", marketPriceMin: "9500.00", marketPriceMax: "18000.00", stockQuantity: 8, warranty: "3 Months" },

    // ===== SIDE MIRRORS =====
    { sku: "SM-COR-001", name: "Toyota Corolla Side Mirror (Left)", slug: "toyota-corolla-side-mirror-left", description: "Left side mirror for Toyota Corolla with electric adjustment.", specifications: "Position: Left\nAdjustment: Electric\nHeated: No", image: "/images/products/body/side-mirror-generic.jpg", categoryId: catMap["body-parts"], subcategoryId: subMap["side-mirrors"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "2500.00", sellingPrice: "4800.00", marketPriceMin: "4200.00", marketPriceMax: "8500.00", stockQuantity: 12, warranty: "3 Months" },
    { sku: "SM-COR-002", name: "Toyota Corolla Side Mirror (Right)", slug: "toyota-corolla-side-mirror-right", description: "Right side mirror for Toyota Corolla with electric adjustment.", specifications: "Position: Right\nAdjustment: Electric", image: "/images/products/body/side-mirror-generic.jpg", categoryId: catMap["body-parts"], subcategoryId: subMap["side-mirrors"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "2500.00", sellingPrice: "4800.00", marketPriceMin: "4200.00", marketPriceMax: "8500.00", stockQuantity: 12, warranty: "3 Months" },
    { sku: "SM-CIV-001", name: "Honda Civic Side Mirror (Left)", slug: "honda-civic-side-mirror-left", description: "Left side mirror for Honda Civic.", specifications: "Position: Left\nAdjustment: Electric\nWith LED Indicator", image: "/images/products/body/side-mirror-generic.jpg", categoryId: catMap["body-parts"], subcategoryId: subMap["side-mirrors"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "3500.00", sellingPrice: "6800.00", marketPriceMin: "6000.00", marketPriceMax: "12000.00", stockQuantity: 8, warranty: "3 Months" },
    { sku: "SM-SPO-001", name: "Kia Sportage Side Mirror (Left)", slug: "kia-sportage-side-mirror-left", description: "Left side mirror for Kia Sportage with LED indicator.", specifications: "Position: Left\nWith LED Indicator\nElectric Fold", image: "/images/products/body/side-mirror-generic.jpg", categoryId: catMap["body-parts"], subcategoryId: subMap["side-mirrors"], carBrand: "Kia", carModel: "Sportage", yearFrom: 2018, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "5500.00", sellingPrice: "10500.00", marketPriceMin: "9500.00", marketPriceMax: "18000.00", stockQuantity: 6, warranty: "3 Months" },
    { sku: "SM-ALT-001", name: "Suzuki Alto Side Mirror (Left)", slug: "suzuki-alto-side-mirror-left", description: "Left side mirror for Suzuki Alto. Manual adjustment.", specifications: "Position: Left\nAdjustment: Manual", image: "/images/products/body/side-mirror-generic.jpg", categoryId: catMap["body-parts"], subcategoryId: subMap["side-mirrors"], carBrand: "Suzuki", carModel: "Alto", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "1200.00", sellingPrice: "2200.00", marketPriceMin: "1800.00", marketPriceMax: "3500.00", stockQuantity: 20, warranty: "3 Months" },

    // ===== ENGINE OIL =====
    { sku: "EO-5W30-4L", name: "5W-30 Synthetic Engine Oil (4 Liter)", slug: "5w30-synthetic-engine-oil-4l", description: "Fully synthetic engine oil. Suitable for modern cars.", specifications: "Viscosity: 5W-30\nType: Fully Synthetic\nVolume: 4 Liters", image: "/images/products/oils/engine-oil-generic.jpg", categoryId: catMap["oils-fluids"], subcategoryId: subMap["engine-oil"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "2500.00", sellingPrice: "4800.00", marketPriceMin: "4200.00", marketPriceMax: "8000.00", stockQuantity: 30, warranty: "No warranty" },
    { sku: "EO-10W40-4L", name: "10W-40 Semi Synthetic Engine Oil (4 Liter)", slug: "10w40-semi-synthetic-engine-oil-4l", description: "Semi synthetic engine oil. Good for all weather conditions.", specifications: "Viscosity: 10W-40\nType: Semi Synthetic\nVolume: 4 Liters", image: "/images/products/oils/engine-oil-generic.jpg", categoryId: catMap["oils-fluids"], subcategoryId: subMap["engine-oil"], carBrand: "Suzuki", carModel: "Cultus", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "2000.00", sellingPrice: "3800.00", marketPriceMin: "3200.00", marketPriceMax: "6000.00", stockQuantity: 40, warranty: "No warranty" },
    { sku: "EO-0W20-4L", name: "0W-20 Full Synthetic Engine Oil (4 Liter)", slug: "0w20-full-synthetic-engine-oil-4l", description: "Advanced full synthetic oil for hybrid and modern engines.", specifications: "Viscosity: 0W-20\nType: Full Synthetic\nVolume: 4 Liters", image: "/images/products/oils/engine-oil-generic.jpg", categoryId: catMap["oils-fluids"], subcategoryId: subMap["engine-oil"], carBrand: "Honda", carModel: "Civic", yearFrom: 2016, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "3500.00", sellingPrice: "6800.00", marketPriceMin: "6000.00", marketPriceMax: "12000.00", stockQuantity: 25, warranty: "No warranty" },
    { sku: "EO-20W50-4L", name: "20W-50 Mineral Engine Oil (4 Liter)", slug: "20w50-mineral-engine-oil-4l", description: "Mineral engine oil for older vehicles.", specifications: "Viscosity: 20W-50\nType: Mineral\nVolume: 4 Liters", image: "/images/products/oils/engine-oil-generic.jpg", categoryId: catMap["oils-fluids"], subcategoryId: subMap["engine-oil"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 1990, yearTo: 2010, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "1500.00", sellingPrice: "2800.00", marketPriceMin: "2500.00", marketPriceMax: "4500.00", stockQuantity: 50, warranty: "No warranty" },
    { sku: "EO-5W40-4L", name: "5W-40 Full Synthetic Engine Oil (4 Liter)", slug: "5w40-full-synthetic-engine-oil-4l", description: "Premium full synthetic for European cars.", specifications: "Viscosity: 5W-40\nType: Full Synthetic\nVolume: 4 Liters", image: "/images/products/oils/engine-oil-generic.jpg", categoryId: catMap["oils-fluids"], subcategoryId: subMap["engine-oil"], carBrand: "BMW", carModel: "3 Series", yearFrom: 2005, yearTo: 2024, condition: "new" as const, qualityType: "oem" as const, purchasePrice: "4000.00", sellingPrice: "7800.00", marketPriceMin: "7000.00", marketPriceMax: "14000.00", stockQuantity: 15, warranty: "No warranty" },

    // ===== WIPERS =====
    { sku: "WP-COR-001", name: "Toyota Corolla Wiper Blades (Pair)", slug: "toyota-corolla-wiper-blades", description: "Aero flat wiper blades for Toyota Corolla.", specifications: "Driver: 26 inch\nPassenger: 14 inch\nType: Aero Flat", image: "/images/products/accessories/wipers-generic.jpg", categoryId: catMap["accessories"], subcategoryId: subMap["wipers"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "800.00", sellingPrice: "1500.00", marketPriceMin: "1300.00", marketPriceMax: "2500.00", stockQuantity: 35, warranty: "1 Month" },
    { sku: "WP-CIV-001", name: "Honda Civic Wiper Blades (Pair)", slug: "honda-civic-wiper-blades", description: "Aero flat wiper blades for Honda Civic.", specifications: "Driver: 26 inch\nPassenger: 18 inch", image: "/images/products/accessories/wipers-generic.jpg", categoryId: catMap["accessories"], subcategoryId: subMap["wipers"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "850.00", sellingPrice: "1600.00", marketPriceMin: "1400.00", marketPriceMax: "2800.00", stockQuantity: 30, warranty: "1 Month" },
    { sku: "WP-ALT-001", name: "Suzuki Alto Wiper Blades (Pair)", slug: "suzuki-alto-wiper-blades", description: "Aero flat wiper blades for Suzuki Alto.", specifications: "Driver: 18 inch\nPassenger: 16 inch", image: "/images/products/accessories/wipers-generic.jpg", categoryId: catMap["accessories"], subcategoryId: subMap["wipers"], carBrand: "Suzuki", carModel: "Alto", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "500.00", sellingPrice: "950.00", marketPriceMin: "800.00", marketPriceMax: "1600.00", stockQuantity: 50, warranty: "1 Month" },
    { sku: "WP-SPO-001", name: "Kia Sportage Wiper Blades (Pair)", slug: "kia-sportage-wiper-blades", description: "Aero flat wiper blades for Kia Sportage.", specifications: "Driver: 26 inch\nPassenger: 16 inch", image: "/images/products/accessories/wipers-generic.jpg", categoryId: catMap["accessories"], subcategoryId: subMap["wipers"], carBrand: "Kia", carModel: "Sportage", yearFrom: 2018, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "1000.00", sellingPrice: "1900.00", marketPriceMin: "1600.00", marketPriceMax: "3200.00", stockQuantity: 20, warranty: "1 Month" },

    // ===== FLOOR MATS =====
    { sku: "FM-COR-001", name: "Toyota Corolla 3D Floor Mats (Set)", slug: "toyota-corolla-floor-mats", description: "3D custom fit floor mats for Toyota Corolla. Waterproof and durable.", specifications: "Material: PVC\nType: 3D Custom Fit\nSet: 4 pieces", image: "/images/products/accessories/floor-mats-generic.jpg", categoryId: catMap["accessories"], subcategoryId: subMap["floor-mats"], carBrand: "Toyota", carModel: "Corolla", yearFrom: 2002, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "1500.00", sellingPrice: "2800.00", marketPriceMin: "2500.00", marketPriceMax: "5000.00", stockQuantity: 25, warranty: "No warranty" },
    { sku: "FM-CIV-001", name: "Honda Civic 3D Floor Mats (Set)", slug: "honda-civic-floor-mats", description: "3D custom fit floor mats for Honda Civic.", specifications: "Material: PVC\nType: 3D Custom Fit\nSet: 4 pieces", image: "/images/products/accessories/floor-mats-generic.jpg", categoryId: catMap["accessories"], subcategoryId: subMap["floor-mats"], carBrand: "Honda", carModel: "Civic", yearFrom: 2001, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "1600.00", sellingPrice: "3000.00", marketPriceMin: "2600.00", marketPriceMax: "5200.00", stockQuantity: 22, warranty: "No warranty" },
    { sku: "FM-ALT-001", name: "Suzuki Alto 3D Floor Mats (Set)", slug: "suzuki-alto-floor-mats", description: "3D custom fit floor mats for Suzuki Alto.", specifications: "Material: PVC\nType: 3D Custom Fit", image: "/images/products/accessories/floor-mats-generic.jpg", categoryId: catMap["accessories"], subcategoryId: subMap["floor-mats"], carBrand: "Suzuki", carModel: "Alto", yearFrom: 2000, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "1000.00", sellingPrice: "1900.00", marketPriceMin: "1600.00", marketPriceMax: "3200.00", stockQuantity: 35, warranty: "No warranty" },
    { sku: "FM-SPO-001", name: "Kia Sportage 3D Floor Mats (Set)", slug: "kia-sportage-floor-mats", description: "3D custom fit floor mats for Kia Sportage.", specifications: "Material: PVC\nType: 3D Custom Fit\nSet: 5 pieces", image: "/images/products/accessories/floor-mats-generic.jpg", categoryId: catMap["accessories"], subcategoryId: subMap["floor-mats"], carBrand: "Kia", carModel: "Sportage", yearFrom: 2018, yearTo: 2024, condition: "new" as const, qualityType: "aftermarket" as const, purchasePrice: "2000.00", sellingPrice: "3800.00", marketPriceMin: "3200.00", marketPriceMax: "6500.00", stockQuantity: 15, warranty: "No warranty" },
  ];

  for (const product of productData) {
    await db.insert(products).values(product).onDuplicateKeyUpdate({
      set: { ...product, updatedAt: new Date() },
    });
  }

  // ==================== DEFAULT SETTINGS ====================
  console.log("Inserting default settings...");
  const defaultSettings = [
    { key: "shopName", value: "Auto Parts Shop" },
    { key: "shopAddress", value: "Main Auto Market, Karachi, Pakistan" },
    { key: "shopPhone", value: "03XX-XXXXXXX" },
    { key: "shopWhatsapp", value: "03XX-XXXXXXX" },
    { key: "shopEmail", value: "info@autopartsshop.pk" },
    { key: "googleMapsUrl", value: "https://maps.google.com" },
    { key: "openingHours", value: "Mon-Sat: 9:00 AM - 8:00 PM, Sun: Closed" },
    { key: "easypaisaNumber", value: "03XX-XXXXXXX" },
    { key: "jazzcashNumber", value: "03XX-XXXXXXX" },
    { key: "bankName", value: "Your Bank Name" },
    { key: "bankAccountTitle", value: "Auto Parts Shop" },
    { key: "bankAccountNumber", value: "XXXXXXXXXX" },
    { key: "bankIban", value: "PKXX XXXX XXXX XXXX XXXX XXXX" },
    { key: "deliveryCharge", value: "200" },
    { key: "serviceFee", value: "0" },
    { key: "codEnabled", value: "true" },
    { key: "returnPolicy", value: "7 days replacement warranty on all products. Items must be in original condition with receipt." },
    { key: "privacyPolicy", value: "We value your privacy. Your personal information is secure with us." },
    { key: "termsAndConditions", value: "By using our services, you agree to our terms and conditions." },
    { key: "facebookUrl", value: "" },
    { key: "instagramUrl", value: "" },
    { key: "youtubeUrl", value: "" },
  ];

  for (const setting of defaultSettings) {
    await db.insert(websiteSettings).values(setting).onDuplicateKeyUpdate({
      set: setting,
    });
  }

  console.log("Seed completed successfully!");
}

seed().catch(console.error);
